### ISSUE TITLE
make sure your redirect_uri is identical, facebook api 2.5

### ISSUE THREAD

**Issue by pywebdesign** [mkdynamic/omniauth-facebook#220]
On a new installation of rails, devise and omniauth-facebook I get this error. Maybe version 2.5 broke something? do any have an idea what it is or experienced the same problem? thank you

ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, : 
web_1 | {"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request","type":"OAuthException","code":100,"fbtrace_id":"EH461ou3pWE"}}

Full trace
 Started GET "/users/auth/facebook/callback?code=AQCOB_jcupsTF...adM&state=1ec...184" for 172.17.42.1 at 2015-10-22 13:08:59 +0000
web_1 | I, [2015-10-22T13:08:59.409907 #1]  INFO -- omniauth: (facebook) Callback phase initiated.
web_1 | E, [2015-10-22T13:08:59.674210 #1] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, : 
web_1 | {"error":{"message":"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request","type":"OAuthException","code":100,"fbtrace_id":"EH461ou3pWE"}}
web_1 | Processing by Users::OmniauthCallbacksController#failure as HTML
web_1 |   Parameters: {"code"=>"AQCO...DadM", "state"=>"1ec0...184"}
web_1 | Redirected to http://localhost:3000/users/sign_in
web_1 | Completed 302 Found in 1ms (ActiveRecord: 0.0ms)

**Comment by bnhansn** [comment]
I am having the same issue with devise & omniauth facebook. In `devise.rb` I tried to explicitly set `callback_path: /users/auth/facebook/callback` and now my controller endpoint is successfully being reached, but `request.env["omniauth.auth"]` is nil. Ideas anyone?

**Comment by gioblu** [comment]
I have the same issue. Happens because the redirect_uri contains also the code parameter. I have fixed with this modification: https://github.com/gioblu/omniauth-facebook/commit/eff97bfae32f72821cbccf0b48b78351e41eb585

If you perceive this correct, tell me and I will make a pull request as soon as possible.

**Comment by pywebdesign** [comment]
hi @gioblu,

Amazing fix! it works.

**Comment by bnhansn** [comment]
:thumbsup: @gioblu that fixes it

**Comment by K1N5L4Y3R** [comment]
@gioblu awesome fix. Thanks!

**Comment by knowyrrole101** [comment]
I am still experiencing this issue where request.env['ominauth.auth'] is null if I pass in callback url :callback_url => 'http://localhost:3000/sessions/create'. I am not using devise, only omniauth-fb gem. If I dont enter the callback URL in initializers/omniauth.rb i get the redirect URI error as listed above. Appreciate any help! :)

**Comment by bmalehorn** [comment]
Perhaps this isn't the place to ask, but maybe this warrants a new release / push to gems?

Right now, 100% of people trying to set up Facebook + Rails are getting this error. It's "broken on production" in a sense. Doesn't that mean a new version should be pushed out soon?

**Comment by knowyrrole101** [comment]
Thanks for the fix!! I do agree with bmalehorn, however.

**Comment by wraithseeker** [comment]
Does anyone know where I should be editing those files in lib/omniauth/strategies/facebook.rb when testing on my local machine?

**Comment by knowyrrole101** [comment]
Edit the gem itself locally.. replace || super in the callback method with
the code fix.

**Comment by mkdynamic** [comment]
Fix released in 3.0.0.

**Comment by amrokhudair** [comment]
@gioblu  I have the same problem , the gioblu/omniauth-facebook@eff97bf does not exist.

**Comment by fabriziobertoglio1987** [comment]
I also have problems with facebook-omniauth callback-url. I receive the following message and I openend a stackoverflow question
"redirect_uri isn't an absolute URI. Check RFC 3986.","type":"OAuthException","code":191,"
http://stackoverflow.com/questions/42549803/devise-omniauth-facebook-redirect-uri-isnt-an-absolute-uri
